apiVersion: apps/v1
kind: Deployment
metadata:
  name: comversortemp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: ctemp
  template:
    metadata:
      labels:
        app: ctemp
    spec:
      containers:
      - name: web
        image: tmfonseca/coversor-temp:v1
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: ctemp
spec:
  selector:
    app: ctemp
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 31000
  type: NodePort
